# Theme of the website
# theme: bulma-clean-theme
# jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

# Title of the website
layout: page
title: Big data course 2025
description: By Firas Jolha

fixed_navbar: top

# collections:
#   products: 
#     output: true
#     layout: product
#     # image: https://via.placeholder.com/800x600
#     show_sidebar: false