# Theme of the website
# theme: bulma-clean-theme
# jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

layout: page

# Title of the website
title: Big data course 2025

# Description
description: By Firas Jolha



